/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParksKandryKulRouteImport } from './routes/parks.kandry-kul'
import { Route as ParksAslyKulRouteImport } from './routes/parks.asly-kul'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksKandryKulRoute = ParksKandryKulRouteImport.update({
  id: '/parks/kandry-kul',
  path: '/parks/kandry-kul',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksAslyKulRoute = ParksAslyKulRouteImport.update({
  id: '/parks/asly-kul',
  path: '/parks/asly-kul',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parks/asly-kul': typeof ParksAslyKulRoute
  '/parks/kandry-kul': typeof ParksKandryKulRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parks/asly-kul': typeof ParksAslyKulRoute
  '/parks/kandry-kul': typeof ParksKandryKulRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parks/asly-kul': typeof ParksAslyKulRoute
  '/parks/kandry-kul': typeof ParksKandryKulRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parks/asly-kul' | '/parks/kandry-kul'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parks/asly-kul' | '/parks/kandry-kul'
  id: '__root__' | '/' | '/parks/asly-kul' | '/parks/kandry-kul'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParksAslyKulRoute: typeof ParksAslyKulRoute
  ParksKandryKulRoute: typeof ParksKandryKulRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/kandry-kul': {
      id: '/parks/kandry-kul'
      path: '/parks/kandry-kul'
      fullPath: '/parks/kandry-kul'
      preLoaderRoute: typeof ParksKandryKulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/asly-kul': {
      id: '/parks/asly-kul'
      path: '/parks/asly-kul'
      fullPath: '/parks/asly-kul'
      preLoaderRoute: typeof ParksAslyKulRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParksAslyKulRoute: ParksAslyKulRoute,
  ParksKandryKulRoute: ParksKandryKulRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
